# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BMI_Calculator(object):
    def setupUi(self, BMI_Calculator):
        BMI_Calculator.setObjectName("BMI_Calculator")
        BMI_Calculator.resize(640, 437)
        self.centralwidget = QtWidgets.QWidget(BMI_Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.height_input = QtWidgets.QLineEdit(self.centralwidget)
        self.height_input.setGeometry(QtCore.QRect(210, 90, 131, 21))
        self.height_input.setObjectName("height_input")
        self.weight_input = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_input.setGeometry(QtCore.QRect(210, 140, 131, 21))
        self.weight_input.setObjectName("weight_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(4, 5, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.calculate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_btn.setGeometry(QtCore.QRect(250, 190, 141, 31))
        self.calculate_btn.setFlat(False)
        self.calculate_btn.setObjectName("calculate_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 230, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.bmi_result = QtWidgets.QLabel(self.centralwidget)
        self.bmi_result.setGeometry(QtCore.QRect(320, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bmi_result.setFont(font)
        self.bmi_result.setText("")
        self.bmi_result.setObjectName("bmi_result")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(354, 85, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(354, 135, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(4, 270, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.state.setFont(font)
        self.state.setText("")
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(450, 330, 93, 28))
        self.clear_btn.setObjectName("clear_btn")
        BMI_Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BMI_Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        BMI_Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BMI_Calculator)
        self.statusbar.setObjectName("statusbar")
        BMI_Calculator.setStatusBar(self.statusbar)

        self.retranslateUi(BMI_Calculator)
        QtCore.QMetaObject.connectSlotsByName(BMI_Calculator)

    def retranslateUi(self, BMI_Calculator):
        _translate = QtCore.QCoreApplication.translate
        BMI_Calculator.setWindowTitle(_translate("BMI_Calculator", "MainWindow"))
        self.label.setText(_translate("BMI_Calculator", "Height"))
        self.label_2.setText(_translate("BMI_Calculator", "Weight"))
        self.label_3.setText(_translate("BMI_Calculator", "BMI Calculator"))
        self.calculate_btn.setText(_translate("BMI_Calculator", "Calculate"))
        self.label_4.setText(_translate("BMI_Calculator", "BMI = "))
        self.label_5.setText(_translate("BMI_Calculator", "in cm"))
        self.label_6.setText(_translate("BMI_Calculator", "in kg"))
        self.clear_btn.setText(_translate("BMI_Calculator", "Clear"))

